apiVersion: v1
kind: Service
metadata:
  name: catalystx-api-service
spec:
  selector:
    app: catalystx-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort   
#  type: ClusterIP   
#  type: LoadBalancer   

